### ISSUE TITLE
Spreadsheet File

### ISSUE THREAD

**Issue by apahlloXII** [Boaztheostrich/8x8-matrix-using-matrix-creation-software-and-excel#1]
Hey, thanks so much for figuring this out.
I've been fighting with my 16x16 matrix for a week now.

The spreadsheet links you've posted just lead to un-editable html pages.
Could you upload the Spreadsheet/Excel file please? (I've got zero spreadsheet/excel experience)

**Comment by Boaztheostrich** [comment]
sure I added it to the front page and gave it its own section lmk if that works I have it as an excel file but you should be able to open it in whatever software you want

**Comment by Boaztheostrich** [comment]
[heres a linkg](https://github.com/Boaztheostrich/8x8-matrix-using-matrix-creation-software-and-excel/blob/main/Led%208x8%20matrix%20v2%20gif%20support.xlsx)

**Comment by Boaztheostrich** [comment]
Let me know if you need anymore help but you should be able to just push download or view raw and it will automatically download
